/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.border.TitledBorder;

/**
 * 数据完整性验证面板
 * @author b1106
 */
public class IntegrityPanel extends javax.swing.JPanel {

    ArrayList<JTextArea> taResults;
    NodePanel nodePanel;

    /**
     * Creates new form IntegrityPanel
     */
    public IntegrityPanel() {
        initComponents();
        taResults = new ArrayList<JTextArea>();
    }

    /**
     * 初始化面板
     * @param nodePanel 
     */
    public void init(NodePanel nodePanel) {
        this.nodePanel = nodePanel;
//        repaint();
        removeAll();
        taResults.clear();
        int len = nodePanel.getNodeProcess().size();
        String[] strs = new String[len];
        for (int i = 0; i < len; i++) {
            strs[i] = nodePanel.getNodeProcess().get(i).getText();
        }
        setTextAreas(strs);
    }

    /**
     * 根据过程信息设置信息展示面板
     * @param strs  面板标题
     */
    public void setTextAreas(String[] strs) {
        int num = strs.length;
        for (int i = 0; i < num; i++) {
            JTextArea ta = new JTextArea();
            ta.setColumns(20);
            ta.setRows(5);
            ta.setBorder(null);
            ta.setLineWrap(true);
            taResults.add(ta);
//            add(ta);
            JScrollPane js = new JScrollPane();
            js.setViewportBorder(BorderFactory.createTitledBorder(null, strs[i], TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION));
            js.setViewportView(ta);
            add(js);
            revalidate();
            repaint();
        }
    }

    /**
     * 添加信息接口
     * @param index 信息展示面板索引
     * @param text 信息
     */
    public void appendResult(int index, String text) {
        taResults.get(index).append(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(1, 0));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
