/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.border.TitledBorder;
import main.NodePanel;

/**
 *
 * @author shuai
 */
public class ResultDialog extends javax.swing.JDialog {

    ArrayList<JTextArea> taResults;
    private NodePanel nodePanel;

    /**
     * Creates new form ResultDialog
     */
    public ResultDialog(java.awt.Frame parent, boolean modal, NodePanel nodePanel) {
        super(parent, modal);
        initComponents();
        taResults = new ArrayList<JTextArea>();
        this.nodePanel = nodePanel;
    }

    public void init() {
        getContentPane().removeAll();
        repaint();
        taResults.clear();
        int len = nodePanel.getNodeProcess().size();
        String[] strs = new String[len];
        for (int i = 0; i < len; i++) {
            strs[i] = nodePanel.getNodeProcess().get(i).getText();
        }
        setTextAreas(strs);
        setSize(len * 200, 300);
        setLocationRelativeTo(null);
    }

    public void setTextAreas(String[] strs) {
        int num = strs.length;
        for (int i = 0; i < num; i++) {
            JTextArea ta = new JTextArea();
            ta.setColumns(20);
            ta.setRows(5);
            ta.setBorder(null);
            ta.setLineWrap(true);
            taResults.add(ta);
            JScrollPane js = new JScrollPane();
            js.setViewportBorder(BorderFactory.createTitledBorder(null, strs[i], TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION));
            js.setViewportView(ta);
            add(js);
        }
    }

    public void setResult(int index, String text) {
        taResults.get(index).setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getContentPane().setLayout(new java.awt.GridLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ResultDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ResultDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ResultDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ResultDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ResultDialog dialog = new ResultDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
